import {isAdmin,sameOrigin} from '../../../lib/auth';
import {readContent,readMessages,saveContent} from '../../../lib/db';
import {adminClient} from '../../../lib/supabase/admin';
import {cleanHtml,mediaUrl} from '../../../lib/sanitize';
import {z} from 'zod';
const entry=z.object({id:z.string().min(1).max(100),type:z.enum(['service','project','news','page','document']),title:z.string().min(1).max(160),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(100),summary:z.string().max(2000),body:z.string().max(100000),image:z.string().refine(mediaUrl),file:z.string().refine(mediaUrl),category:z.string().max(120),published:z.boolean(),seoTitle:z.string().max(200),seoDescription:z.string().max(500)});
const settings=z.object({company:z.string().min(1).max(160),heroTitle:z.string().max(200),heroText:z.string().max(600),heroImage:z.string().refine(mediaUrl),logo:z.string().refine(mediaUrl),footerLogo:z.string().refine(mediaUrl),about:z.string().max(100000),email:z.union([z.literal(''),z.string().email()]),phone:z.string().max(60),address:z.string().max(500),seoTitle:z.string().max(200),seoDescription:z.string().max(500)});
export async function GET(){if(!await isAdmin())return Response.json({error:'Akses admin diperlukan.'},{status:403});try{const content=await readContent();const messages=await readMessages();return Response.json({...content,messages},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:'Konten belum dapat dimuat. Coba kembali.'},{status:503});}}
export async function PUT(request:Request){if(!sameOrigin(request)||!await isAdmin())return Response.json({error:'Akses ditolak.'},{status:403});try{const {data,version}=z.object({data:z.object({settings,entries:z.array(entry).max(300)}),version:z.number().int().nonnegative()}).parse(await request.json());const paths=data.entries.map(e=>e.type==='page'?e.slug:e.type+'/'+e.slug);if(new Set(paths).size!==paths.length||new Set(data.entries.map(e=>e.id)).size!==data.entries.length)return Response.json({error:'Slug atau identitas konten duplikat.'},{status:400});if(data.entries.some(e=>e.type==='page'&&['admin','api','media','layanan','perusahaan','proyek','berita','kontak','unduhan','signin-with-chatgpt','signout-with-chatgpt','callback','auth'].includes(e.slug)))return Response.json({error:'Slug halaman ini sudah digunakan.'},{status:400});data.settings.about=cleanHtml(data.settings.about);data.entries.forEach(e=>e.body=cleanHtml(e.body));const saved=await saveContent(data,version);if(saved===null)return Response.json({error:'Konten telah berubah di sesi lain. Muat ulang sebelum menyimpan.'},{status:409});return Response.json({version:saved,data});}catch(e){console.error(e);return Response.json({error:e instanceof z.ZodError?'Periksa judul, slug, dan data yang diisi.':'Penyimpanan gagal. Perubahan Anda masih tersedia di editor.'},{status:e instanceof z.ZodError?400:503});}}
export async function PATCH(request:Request){if(!sameOrigin(request)||!await isAdmin())return Response.json({error:'Akses ditolak.'},{status:403});try{const p=z.object({id:z.string(),status:z.enum(['new','read'])}).parse(await request.json());const {error}=await adminClient().from('rama_contact_messages').update({status:p.status}).eq('id',p.id);if(error)throw error;return Response.json({ok:true});}catch{return Response.json({error:'Status gagal diubah.'},{status:503});}}
