// Company Profile, version 2, updated 5 October 2026 (18 slides).
// Illustrative deck photographs are intentionally not used as project records.
export const companyContact = {
  email: "ramasaragihsejahtera@gmail.com",
  additionalEmails: ["purbarama09@gmail.com"],
  phone: "+62 831 3457 7149",
  additionalPhones: ["+62 822 7686 0182", "+62 812 8248 1837"],
  address: "Jalan Amal Luhur Lingkungan VIII No. 134\nKelurahan Dwikora, Kecamatan Medan Helvetia\nMedan 20123, Indonesia",
  branchAddress: "Jalan Jalur Sutera Bar, Alam Sutera No. 38 K, Lantai 7\nPanunggangan Tim, Kecamatan Pinang\nBanten 15143, Indonesia",
};
export const servicePrinciples = `<h2>Kebijakan dan Prinsip Layanan</h2><p>Kami berkomitmen pada kepuasan pelanggan dan pemenuhan persyaratan yang berlaku melalui peningkatan produk dan layanan, pencegahan kecelakaan kerja dan penyakit akibat kerja, serta pencegahan pencemaran lingkungan. Pengelolaan mutu, kesehatan dan keselamatan kerja, serta lingkungan diterapkan dalam kegiatan perusahaan dengan dukungan manajemen puncak.</p><ul><li><strong>Responsif:</strong> mengutamakan penanganan kebutuhan pelanggan secara cepat.</li><li><strong>Berorientasi pada mutu:</strong> menyediakan produk bermutu dengan dukungan tenaga yang kompeten.</li><li><strong>Profesional:</strong> menerapkan praktik kerja profesional dalam setiap layanan.</li><li><strong>Andal:</strong> memenuhi kriteria yang disepakati serta mengutamakan penggunaan yang aman dan dapat dipercaya.</li></ul>`;
export const profilePages = [
  {
    slug: "visi-misi", title: "Visi & Misi",
    summary: "Arah pengembangan perusahaan, tata kelola, dan komitmen peningkatan berkelanjutan.",
    body: `<h2>Visi Perusahaan</h2><p>Menjadi pengembang swasta nasional terdepan di bidang perdagangan dan jasa konstruksi dengan menerapkan Total Quality Management (TQM) dan Total Improvement Management (TIM) untuk memberikan mutu pelayanan yang menyeluruh.</p><p>Kami mengutamakan mutu layanan serta kesehatan dan keselamatan kerja dalam seluruh kegiatan perusahaan. Perencanaan solusi konstruksi yang tepat, berkualitas, dan terjangkau merupakan bagian dari komitmen kami.</p><p>Produk bermutu, ketepatan waktu pelaksanaan, serta layanan yang efektif dan dapat dipercaya menjadi landasan keberhasilan. Kami membangun kemitraan jangka panjang berdasarkan kepercayaan dan kepuasan pelanggan.</p><h2>Misi Perusahaan</h2><ol><li><strong>Pelayanan dan tata kelola:</strong> memberikan kualitas, pelayanan, dan kepuasan pelanggan melalui tata kelola perusahaan yang baik.</li><li><strong>Kontribusi pada pembangunan nasional:</strong> mendukung pembangunan Indonesia melalui inisiatif energi baru terbarukan dan konservasi energi (EBTKE).</li><li><strong>Konstruksi yang bertanggung jawab:</strong> mengutamakan mutu serta kesehatan dan keselamatan kerja, sekaligus menciptakan nilai tambah bagi para pemangku kepentingan.</li></ol><h2>Peningkatan Berkelanjutan</h2><p>Kerangka pengelolaan terpadu meliputi persyaratan umum, kebijakan, perencanaan, pelaksanaan dan operasi, penilaian kinerja, perbaikan, serta tinjauan manajemen.</p><p>Dokumen profil merujuk pada ISO 9001:2015, OHSAS 18001:2007, dan ISO 14001:2015 sebagai referensi kerangka pengelolaan.</p>`,
  },
  {
    slug: "struktur-organisasi", title: "Struktur Organisasi",
    summary: "Pengurus, manajemen proyek, dan tim pendukung PT Rama Saragih Sejahtera.",
    body: `<h2>Pengurus dan Pimpinan</h2><table><thead><tr><th>Jabatan</th><th>Nama</th></tr></thead><tbody><tr><td>Komisaris</td><td>Ilham Wahyudi</td></tr><tr><td>Komisaris</td><td>Muhammad Rafli</td></tr><tr><td>Direktur Utama</td><td>Rama Br. Saragih</td></tr><tr><td>Direktur</td><td>Syaifuddin Siregar</td></tr><tr><td>Direktur Operasional</td><td>Ir. Nurja’far Marpaung</td></tr><tr><td>HRGA</td><td>Tiaa</td></tr><tr><td>Project Director</td><td>Anang Juniawan, ST, MM</td></tr></tbody></table><h2>Manajemen Proyek dan Pendukung</h2><table><thead><tr><th>Jabatan</th><th>Nama</th></tr></thead><tbody><tr><td>Project Manager</td><td>Erwunarto, ST</td></tr><tr><td>Project Manager</td><td>Beni Sugiarto</td></tr><tr><td>Marketing Manager</td><td>Komala Dewi</td></tr><tr><td>Accounting Manager</td><td>Yenni Kharish</td></tr><tr><td>Project Engineer</td><td>Dedi Zaro</td></tr><tr><td>Accounting Admin</td><td>Sri Hartati</td></tr></tbody></table><h2>Koordinasi Lapangan</h2><table><thead><tr><th>Fungsi</th><th>Nama</th></tr></thead><tbody><tr><td>Project Control</td><td>Indra Kamil</td></tr><tr><td>HSE (K3L)</td><td>Dufri Risyad</td></tr><tr><td>Warehouse</td><td>Fadlan Siregar</td></tr><tr><td>General Support</td><td>Tomy</td></tr><tr><td>HSE Admin (K3L)</td><td>Siti Saleha</td></tr></tbody></table><p>Koordinasi pelaksanaan didukung oleh tim proyek sesuai fungsi dan tanggung jawab masing-masing.</p>`,
  },
  {
    slug: "qhsse", title: "Kebijakan QHSSE",
    summary: "Komitmen terhadap mutu, kesehatan, keselamatan, keamanan, dan lingkungan.",
    body: `<h2>Quality, Health, Safety, Security & Environment</h2><p>PT Rama Saragih Sejahtera berkomitmen pada kepuasan pelanggan, tempat kerja yang aman dan sehat bagi karyawan dan mitra, serta perlindungan lingkungan. Peningkatan berkelanjutan dalam pengelolaan keselamatan dan kesehatan kerja serta lingkungan mendukung komitmen ini.</p><p>Kebijakan berlaku bagi direksi, karyawan, dan mitra sesuai tanggung jawab masing-masing.</p><h2>Komitmen Perusahaan</h2><ol><li><strong>Kepatuhan:</strong> mengutamakan QHSSE untuk memenuhi peraturan dan standar yang berlaku.</li><li><strong>Identifikasi risiko:</strong> mengidentifikasi bahaya, risiko keamanan, dan aspek lingkungan dalam setiap kegiatan untuk mencegah cedera, kerusakan peralatan, gangguan keamanan, dan pencemaran.</li><li><strong>Partisipasi:</strong> melibatkan karyawan dan mitra dalam menjaga mutu, kesehatan, keselamatan, keamanan, dan lingkungan.</li><li><strong>Teknologi dan sumber daya:</strong> menggunakan teknologi dan sumber daya kerja yang tepat untuk mengurangi risiko terhadap manusia, aset, lingkungan, dan reputasi perusahaan, sekaligus memenuhi persyaratan produk pelanggan.</li><li><strong>Kinerja dan penghargaan:</strong> memasukkan kinerja mutu serta kesehatan dan keselamatan kerja ke dalam penilaian dan penghargaan bagi karyawan dan mitra.</li><li><strong>Kompetensi dan budaya kerja:</strong> meningkatkan kompetensi, kesadaran, dan budaya kerja untuk mendukung pekerjaan produktif dan efisien yang memenuhi standar QHSSE.</li><li><strong>Hubungan pemangku kepentingan:</strong> mengembangkan hubungan harmonis di sekitar kegiatan operasional dan kemitraan yang saling menguntungkan.</li><li><strong>Perlindungan lingkungan:</strong> menjalankan program lingkungan dalam kegiatan perusahaan dan wilayah sekitarnya serta meningkatkan kesadaran konservasi.</li><li><strong>Peningkatan terpadu:</strong> mengukur dan meningkatkan kinerja pengelolaan QHSSE secara berkelanjutan sebagai satu sistem terpadu.</li></ol><p>Medan, 2 Januari 2025<br>Rama Br. Saragih — Direktur Utama</p>`,
  },
  {
    slug: "kebijakan-keselamatan", title: "Kebijakan Keselamatan Kerja",
    summary: "Peraturan merokok, obat-obatan terlarang, dan minuman keras di lingkungan kerja.",
    body: `<h2>Lingkungan Kerja yang Aman dan Sehat</h2><p>Kebijakan ini melindungi kesehatan, keselamatan, dan produktivitas. Ketentuan berlaku bagi karyawan, kontraktor, pengunjung, dan tenaga kerja sementara.</p><h2>Larangan</h2><ul><li>Menggunakan, memiliki, memasok, membawa, atau menjual narkotika, obat-obatan terlarang, minuman keras, atau alkohol.</li><li>Merokok di luar area yang telah ditentukan.</li></ul><h2>Pelaksanaan dan Sosialisasi</h2><p>Pelanggaran dikenakan sanksi sesuai peraturan perundang-undangan dan peraturan perusahaan yang berlaku. Pimpinan unit kerja wajib menyampaikan kebijakan ini kepada seluruh pekerja dan pihak terkait.</p>`,
  },
];
