export type Entry={id:string;type:'service'|'project'|'news'|'page'|'document';title:string;slug:string;summary:string;body:string;image:string;file:string;category:string;published:boolean;seoTitle:string;seoDescription:string};
export type Settings={company:string;heroTitle:string;heroText:string;heroImage:string;logo:string;footerLogo:string;about:string;email:string;phone:string;address:string;seoTitle:string;seoDescription:string};
export type Content={settings:Settings;entries:Entry[]};
const services=[
['Mekanikal','mekanikal','Pekerjaan mekanikal untuk kebutuhan fasilitas industri.','Ruang lingkup meliputi pemasangan dan pekerjaan peralatan mekanikal sesuai kebutuhan proyek. Penggunaan peralatan yang efisien dan koordinasi lapangan menjadi bagian dari pendekatan pelaksanaan.'],
['Isolasi','isolasi','Pekerjaan isolasi pada pipa dan peralatan industri.','Layanan isolasi mendukung kebutuhan operasional pipa dan peralatan industri. Material, metode, dan ruang lingkup pekerjaan disesuaikan dengan spesifikasi teknis yang disepakati.'],
['PWHT Service','pwht-service','Post Weld Heat Treatment untuk kebutuhan pekerjaan pengelasan.','Pelaksanaan Post Weld Heat Treatment (PWHT) disesuaikan dengan persyaratan teknis pekerjaan, material, dan kebutuhan proyek. Koordinasi proses menjadi bagian penting dari pengendalian mutu.'],
['Palm Oil Mill','palm-oil-mill','Dukungan konstruksi dan pekerjaan fasilitas pabrik kelapa sawit.','Pekerjaan untuk fasilitas palm oil mill mencakup kebutuhan konstruksi dan instalasi sesuai ruang lingkup yang disepakati. Tim mengoordinasikan sumber daya, peralatan, dan jadwal pelaksanaan.'],
['Sipil & Konstruksi','sipil-konstruksi','Pekerjaan sipil untuk pembangunan dan fasilitas industri.','Pekerjaan sipil direncanakan berdasarkan kebutuhan proyek, dengan perhatian pada biaya, mutu, dan waktu pelaksanaan. Koordinasi yang responsif mendukung keputusan di lapangan.'],
['Blasting & Painting','blasting-painting','Persiapan permukaan dan pengecatan untuk pekerjaan industri.','Layanan blasting dan painting mencakup persiapan permukaan serta aplikasi pelapisan berdasarkan spesifikasi pekerjaan. Pelaksanaan disesuaikan dengan kebutuhan material dan lingkungan operasional.'],
['Fabrikasi','fabrikasi','Fabrikasi komponen dan struktur untuk kebutuhan proyek.','Pekerjaan fabrikasi dilaksanakan berdasarkan gambar dan spesifikasi yang disepakati. Pengelolaan material, peralatan, serta disiplin kerja mendukung hasil dan jadwal yang terencana.'],
['Pipa & Tank Equipment','pipa-tank-equipment','Instalasi perpipaan dan peralatan tangki untuk fasilitas industri.','Pekerjaan instalasi pipa dan tank equipment mendukung kebutuhan fasilitas industri, termasuk sektor minyak dan gas. Ruang lingkup dan metode pelaksanaan mengikuti persyaratan proyek.']
];
export const defaults:Content={settings:{company:'PT Rama Saragih Sejahtera',heroTitle:'Pengalaman yang membangun.\nKetepatan yang dipercaya.',heroText:'Jasa konstruksi, mekanikal, dan solusi industri dengan komitmen pada biaya, mutu, serta waktu pelaksanaan.',heroImage:'/images/industrial-hero.jpg',logo:'/images/logo-rss.png',footerLogo:'/images/logo-rss.png',about:'<p>PT Rama Saragih Sejahtera bergerak di bidang jasa konstruksi dan pekerjaan industri, didukung oleh pengalaman para pengelola yang matang di bidangnya.</p><p>Ruang lingkup usaha kami meliputi mekanikal, isolasi, PWHT service, palm oil mill, sipil, blasting & painting, fabrikasi, serta instalasi pipa dan tank equipment, termasuk kebutuhan sektor minyak dan gas.</p><p>Kami telah bekerja sama dengan sejumlah perusahaan besar dan pabrik berstandar internasional dalam pekerjaan jasa konstruksi maupun penyediaan kebutuhan proyek. Pengalaman ini menjadi landasan untuk mengembangkan layanan di tingkat nasional dan internasional.</p><p>Setiap aktivitas berpedoman pada BMW: Biaya, Mutu, dan Waktu Pelaksanaan yang tepat. Kami mengoptimalkan penggunaan peralatan dan sumber daya, menjalankan disiplin kerja, serta mengutamakan manajemen yang responsif dalam pengambilan keputusan.</p><p>Tujuan kami adalah memberikan manfaat bagi pemberi pekerjaan dan turut berkontribusi dalam pembangunan secara berkelanjutan.</p>',email:'',phone:'',address:'',seoTitle:'PT Rama Saragih Sejahtera | Konstruksi & Solusi Industri',seoDescription:'Jasa mekanikal, isolasi, PWHT, palm oil mill, sipil, blasting painting, fabrikasi, instalasi pipa dan tangki. Berpedoman pada Biaya, Mutu, dan Waktu.'},entries:services.map((s,i)=>({id:'service-'+i,type:'service',title:s[0],slug:s[1],summary:s[2],body:'<p>'+s[3]+'</p>',image:'',file:'',category:i===7?'Minyak & Gas':'Layanan Industri',published:true,seoTitle:s[0]+' | PT Rama Saragih Sejahtera',seoDescription:s[2]}))};
export const sectionTypes:Record<string,Entry['type']>={layanan:'service',proyek:'project',berita:'news',unduhan:'document'};
export const navigation=[['Beranda','/'],['Perusahaan','/perusahaan'],['Layanan','/layanan'],['Proyek','/proyek'],['Berita','/berita']];
export function entryPath(e:Entry){return e.type==='page'?'/'+e.slug:'/'+Object.keys(sectionTypes).find(k=>sectionTypes[k]===e.type)+'/'+e.slug;}
